spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdbcars
    username: team1
    password: passwordHere
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
